[package]
name = "chatter-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "=0.5.1", features = ["json"] }
serde = { version = "1.0.208", features = ["derive"] }
# serde_json = "1.0.125"
log = "0.4.22"
mysql = "25.0.1"
chrono = "0.4.38"
sysinfo = "0.31.3"
